name: RESHEARCH
data:
    src: "text"    # Source - Either Gloss->Pose or Text->Pose (gloss,text)
    trg: "skels"    # Target - 3D body co-ordinates (skels)
    files: "files"    # Filenames for each sequence
    cond: "cond"
    latent: "latent"

    train: "/home/user/Projects/Data/new_phoenix/train"
    dev: "/home/user/Projects/Data/new_phoenix/dev"
    test: "/home/user/Projects/Data/new_phoenix/test"

    max_sent_length: 300 # Max Sentence Length
    skip_frames: 1   # Skip frames in the data, to reduce the data input size
    src_vocab: "/home/user/Projects/research/HoT/dataset/text_src_vocab.txt"

training:
  pretrain: True
  random_seed: 1126   # Random seed for initialisation
  optimizer: "adam"   # Chosen optimiser (adam, ..)
  learning_rate: 0.001   # Initial model learning rate
  learning_rate_min: 0.0002 # Learning rate minimum, when training will stop
  weight_decay: 0.0   # Weight Decay
  clip_grad_norm: 5.0   # Gradient clipping value
  batch_size: 64    # Batch Size for training
  scheduling: "plateau"   # Scheduling at training time (plateau, ...)
  # scheduling: "exponential"   # Scheduling at training time (plateau, ...)
  patience: 7  # How many epochs of no improvement causes a LR reduction
  decrease_factor: 0.7  # LR reduction factor, after the # of patience epochs
  early_stopping_metric: "dtw" # Which metric determines scheduling (DTW, loss, BT...)
  epochs: 1000  # How many epochs to run for
  validation_freq: 2000 # After how many steps to run a validation on the model
  logging_freq: 250  # After how many steps to log training progress
  eval_metric: "dtw"  # Evaluation metric during training (dtw','bt','mpjpe')
  model_dir: "/home/user/Projects/research/HoT/results/token8_phase1_vae" # Where the model shall be stored
  overwrite: False # Flag to overwrite a previous saved model in the model_dir
  continue: True  # Flag to continue from a previous saved model in the model_dir
  shuffle: True  # Flag to shuffle the data during training
  use_cuda: True  # Flag to use GPU cuda capabilities
  max_output_length: 300 # Max Output Length
  keep_last_ckpts: 1 # How many previous best/latest checkpoints to keep
  gpu: 0
  batch_size: 32
  workers: 32
  lr_decay_large: 0.5
  lr_decay_epoch: 200
  lr_decay: 0.99
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  warmup_epochs: 0
  warmup_lr: 1e-6
  cooldow_eopochs: 10
  patience_epochs: 10
  min_lr: 1.0e-08
  decay_epochs: 30
  decay_rate: 0.1  
  wandb: disabled # online or disabled
  scale_embedding: False
  sched: "cosine"

logging:
  chcekpoint: 'checkpoint/'
  previous_dir: 

model:
  trg_size: 150
  n_joints: 50
  out_joints: 50
  qae:
    depth: 1 # Number of layers
    num_heads: 8  # Number of Heads
    num_tokens: 8 # Number of Tokens for Qformer
    hidden_size: 128 # Hidden Size Dimension
    ff_size: 128 # Feed-forward dimension (4 x hidden_size)
    dropout: 0.1 # Encoder Dropout
    drop_rate: 0.1
    drop_path_rate: 0.1
    attn_drop_rate: 0.
    qkv_bias: True
    qk_scale: # None
    max_len: 300
    loss: "L1"
    bone_loss: "MSE"
  text_encoder:
    model_name: "google/gemma-2b"
    hidden_size: 2048
    # model_name: "google/flan-t5-base"
    # hidden_size: 768
